name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: make
      run: make
    - name: Release-Notes-Preview
      uses: snyk/release-notes-preview@v1.6.1
      with:
        releaseBranch: main
